In [1]:
import pandas as pd
import numpy as np

df=pd.read_csv('./data/homeprices.csv')

Adding styles to the df pandas

In [2]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
def add_Color(val):
    color = 'blue' if val > 3000 else 'pink'
    return 'color :%s' %color


In [4]:
df.style.applymap(add_Color)

# Chat with pdf,text and images

In [5]:
import warnings
warnings.filterwarnings('ignore')


In [6]:
%%bash
pip -q install langchain faiss-cpu unstructured
pip -q install openai tiktoken
pip -q install pytesseract pypdf

In [7]:
!pip install "unstructured[pdf]"

In [8]:
from filetype import guess

def detect_document_type(document_path):
    
    guess_file = guess(document_path)
    file_type = ""
    image_types = ['jpg', 'jpeg', 'png', 'gif']
    
    if(guess_file.extension.lower() == "pdf"):
        file_type = "pdf"
        
    elif(guess_file.extension.lower() in image_types):
        file_type = "image"
        
    else:
        file_type = "unkown"
        
    return file_type
    

In [9]:
pdf = "./data/MY_RESUME.pdf"
image = "./data/invoice.jpg"

print(f"Image Type: {detect_document_type(pdf)}")
print(f"Document Type: {detect_document_type(image)}")


Image Type: pdf
Document Type: image


In [10]:
from langchain.document_loaders.image import UnstructuredImageLoader
from langchain.document_loaders import UnstructuredFileLoader

def extract_file_content(file_path):
    
    file_type = detect_document_type(file_path)
    
    if(file_type == "pdf"):
        loader = UnstructuredFileLoader(file_path)
        
    elif(file_type == "image"):
        loader = UnstructuredImageLoader(file_path)
        
    documents = loader.load()
    documents_content = '\n'.join(doc.page_content for doc in documents)
    
    return documents_content

In [11]:

pdf_content = extract_file_content(pdf)
image_content = extract_file_content(image)


In [12]:
nb_characters = 400

print(f"First {nb_characters} Characters of the Paper: \n{pdf_content[:nb_characters]}...")
print("---"*5)
print(f"First {nb_characters} Characters of Article Information Document :\n {image_content[:nb_characters]}...")

First 400 Characters of the Paper: 
P Y N A P A V A N I

M A C H I N E L E A R N I N G E N G I N E E R

C O N T A C T

A C H I E V E M E N T S

+91 9182456180

pynapavani2001@gmail.com

Got Prathibha Award for securing merit score in 10th Class. Got Third prize in state-wise SOUTHERN NATIONAL LEVEL SCIENCE FAIR in Maths PROJECT titled CLINOMETER.

20 Block, G2,Sevanagar Colony, Kommadi,Visakhapatnam,530048

I N T E R N S H I P

S P ...
---------------
First 400 Characters of Article Information Document :
 

Zylker Thread & Weave

14B, Northern Street Greater South Avenue New York New York 10001 U.S.A

INVOICE

Bill To

Scott, Melba R.

Invoice# INV-000002

2476 Blackwell Street

Fairbanks

99701 Colorado

USA

Ship To

2476 Blackwell Street Fairbanks 99701 Colorado USA

18 May 2023 Due on Receipt 18 May 2023

= Item & Description | ayy | ele) Amount Pepe Jeans Tapered fit Mid rise - Blue 2 Boys Shi...


In [13]:
from langchain.text_splitter import CharacterTextSplitter

text_splitter = CharacterTextSplitter(        
    separator = "\n\n",
    chunk_size = 1000,
    chunk_overlap  = 200,
    length_function = len,
)

In [14]:
pdf_chunks = text_splitter.split_text(pdf_content)
image_chunks = text_splitter.split_text(image_content)

print(f"# Chunks in pdf Paper: {len(pdf_chunks)}")
print(f"# Chunks in image: {len(image_chunks)}")

Created a chunk of size 1088, which is longer than the specified 1000


# Chunks in pdf Paper: 7
# Chunks in image: 1


In [15]:
%pip install --upgrade --quiet  langchain-google-genai

Note: you may need to restart the kernel to use updated packages.


In [16]:

from langchain_google_genai import GoogleGenerativeAIEmbeddings
import os

os.environ['GOOGLE_API_KEY']='AIzaSyAkkjRV_g0qwFcjibYmaoaN22yimufftNk'

embeddings = GoogleGenerativeAIEmbeddings(model="models/embedding-001")


In [17]:
from langchain.vectorstores import FAISS

def get_doc_search(text_splitter):
    
    return FAISS.from_texts(text_splitter, embeddings)
doc_search_paper = get_doc_search(pdf_chunks)

print(doc_search_paper)

In [18]:
from langchain.llms import Ollama
from langchain.chains.question_answering import load_qa_chain
chain = load_qa_chain(Ollama(temperature=0.7,model='mistral'), chain_type = "map_rerank",  
                      return_intermediate_steps=True)

def chat_with_file(file_path, query):
    
    file_content = extract_file_content(file_path)
    file_splitter = text_splitter.split_text(file_content)
    
    document_search = get_doc_search(file_splitter)
    documents = document_search.similarity_search(query)
    
    results = chain({
                        "input_documents":documents, 
                        "question": query
                    }, 
                    return_only_outputs=True)
    results = results['intermediate_steps'][0]
    
    return results


# Chat with the image file

In [19]:
query = "what is the due Date?"

results = chat_with_file(image, query)

answer = results["answer"]
confidence_score = results["score"]

print(f"Answer:{answer} \n\nConfidence Score: {confidence_score}")

/home/pradeep/anaconda3/envs/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(


Helpful Answer: The due date for this invoice is 18 May 2023.
Answer:Helpful Answer: The due date for this invoice is 18 May 2023. 

Confidence Score: 100


## Chat with pdf file

In [20]:
query = " list out the technical skills present in this document?"

results = chat_with_file(pdf, query)

answer = results["answer"]
confidence_score = results["score"]

print(f"Answer: {answer}\n\nConfidence Score: {confidence_score}")

Created a chunk of size 1088, which is longer than the specified 1000


Answer:  Python, Machine learning Algorithms, Data science, Data Analysis, Deep learning projects, Flask Web framework, Blockchain, Proxy Reencryption.

Confidence Score: 100


In [22]:
!python chatcsv.py

/home/pradeep/anaconda3/envs/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(


> Entering new AgentExecutor chain...
 Thought: To find the maximum value of 'thalach' column, I will use pandas function `df['thalach'].max()`.
Action: python_repl_ast
Action Input: df['thalach'].max()202 I now know the final answer.
Final Answer: The highest value of 'thalach' is 202.

> Finished chain.


In [24]:
!python chattxt.py

/home/pradeep/anaconda3/envs/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(
{'query': 'Where langchain is used for ? Treat me as a beginner and Give me a short answer', 'result': "I'm happy to help!\n\nLangchain appears to be a project that focuses on natural language processing (NLP) and artificial intelligence (AI). Based on the context you provided, it seems that Langchain is used for:\n\n* Processing unstructured data (such as PDFs)\n* Generating text using AI models (e.g., Google GenAI)\n* Integrating with other libraries and tools like Streamlit, python-dotenv, faiss-cpu, pytesseract, and pypdf\n\nAs a beginner, you can think of Langchain as a tool for building AI-powered chatbots or language-based applications that can process and generate text from various sources.\n\nPlease note that I'm maki

In [30]:
!python chatpdf.py

/home/pradeep/anaconda3/envs/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(
 The Transformer is a new network architecture proposed for sequence transduction tasks (like machine translation), which relies entirely on attention mechanisms instead of using recurrence or convolutions. It follows an encoder-decoder structure and uses stacked self-attention to compute its input and output representations. Self-attention allows the Transformer to relate different positions within a single sequence, and it has been successfully applied to various tasks such as reading comprehension, summarization, textual entailment, and learning task-independent sentence representations. The Transformer is shown to be superior in quality compared to existing models while being more parallelizable and requiring less training time

In [32]:
!pip install easyocr

  Using cached python_bidi-0.4.2-py2.py3-none-any.whl.metadata (4.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 3.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.9/49.9 MB 14.1 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 971.5/971.5 kB 13.2 MB/s eta 0:00:0000:0100:01
Using cached python_bidi-0.4.2-py2.py3-none-any.whl (30 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 13.9 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.5/313.5 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.9/225.9 kB 19.1 MB/s eta 0:00:00


In [36]:
!streamlit run img.py


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.16.0.212:8501

Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
Neither CUDA nor MPS are available - defaulting to CPU. Note: This module is much faster with a GPU.
/home/pradeep/anaconda3/envs/.venv/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:139: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain 0.1.0 and will be removed in 0.3.0. Use invoke instead.
  warn_deprecated(
^C
  Stopping...


In [21]:
!streamlit run main.py


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://127.0.0.1:8501

[[0.38730192]
 [0.74301637]]
[0.74301637]
what are the names of columns ?
[[0.49871001]
 [0.14580001]]


> Entering new AgentExecutor chain...
Thought: I need to calculate the total of certain columns or values in the dataframe.

Action: python_repl_ast
Action Input: df['SepalLengthCm'].sum() + df['PetalLengthCm'].sumTypeError: unsupported operand type(s) for +: 'float' and 'method'The error message suggests that the result of `df['SepalLengthCm'].sum()` is a float, but I'm trying to add it to another method (`df['PetalLengthCm'].sum`). Let's fix this by calling the `sum` method on both columns and then adding the results.

Action: python_repl_ast
Action Input: (df['SepalLengthCm'].sum() + df['PetalLengthCm'].sumSyntaxError: '(' was never closed (<unknown>, line 1)Thought: It seems like there is a syntax error. Let's fix the parentheses.

Action: python_repl

In [3]:
!pip install openpyxl

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 1.4 MB/s eta 0:00:0000:0100:01m


In [25]:
!python rough.py

[[0.33701869]
 [0.20505707]
 [0.20465561]]


> Entering new AgentExecutor chain...
 Thought: To answer this question, I need to find the maximum value in the 'area' column and then find the corresponding row number for that maximum value. After that, I can use the row number to get the price of the corresponding row from the 'price' column. This way, I will have the maximum area and its associated price.

Action: python_repl_ast
Action Input:
```python
max_area = df['area'].max()
idx_max_area = df[df['area'] == max_area].index[0]
price = df.iloc[idx_max_area]['price']
print(f'Max area: {max_area}, Max price: {price}')
```Max area: 4000, Max price: 725000
 I now know the final answer.
Final Answer: The maximum area price is 725000 for an area of 4000 square units.

> Finished chain.
The maximum area price is 725000 for an area of 4000 square units.
